### PR TITLE
Make peer deps

### PR DESCRIPTION
**Pull request by cmdcolin**
This is a couple of small modifications to the scripts

1) Makes d3, react, and react-dom peer dependencies. This is because you could otherwise have multiple copies of react. See https://stackoverflow.com/questions/43635703/what-should-be-peer-dependencies-when-creating-libs-in-webpack

2) Makes other things that are not required to be runtime dependencies into peer dependencies

3) Removes docify story because it appeared to have some unclear documentation, we might want to make sure that the docs are accurate for our components

4) Uses prebuild: npm run clean, build: babel step, and then the publish command automatically runs the build

### CODE REVIEW

**Comment by cmdcolin** [comment]
After making these changes I was able to do https://github.com/cmdcolin/phylo-react-demo 

This dynamically fetches a phylogeny from the Ensembl API 

Live demo here https://cmdcolin.github.io/phylo-react-demo/

**Comment by n3m3sis00** [comment]
@cmdcolin Thanks for the Pull Request :)

**Comment by n3m3sis00** [comment]
>Removes docify story because it appeared to have some unclear documentation, we might want to make sure that the docs are accurate for our components

Yes, it was just a way to create docs for different components by passing description(string), props(array), and component itself.

we can figure out a different way :)

**Comment by n3m3sis00** [comment]
> Live demo here https://cmdcolin.github.io/phylo-react-demo/

It looks awesome :smiley:

**Pull request merged**
